#server.port=8081
#spring.application.name=RoomSeervice
#
#spring.datasource.url=jdbc:postgresql://dpg-d66u78h4tr6s73aj8if0-a.virginia-postgres.render.com/test_data2026?sslmode=require
#spring.datasource.username=bhakti19
#spring.datasource.password=Z2fqeOIzWylY2iSrT2MvfNqzUSvf9g7L
#
#spring.jpa.hibernate.ddl-auto=update
#spring.jpa.show-sql=true
#spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
#
#whatsapp.base.url=https://graph.facebook.com/${whatsapp.server.version}/${whatsapp.phone.number.id}/messages
#whatsapp.phone.number.id=1048663674986407
#whatsapp.server.version=v25.0
#whatsapp.access.token=EAAwkr5IHAgkBQ6X8PQzQAN4b8goUByqLbS8Ptyis4AmsLRPhUxrwcFCxKLwZC11Dd2ZBNk2WWgkjdpzAWGLKoZCDddgBshGj8oLlRtkAmKxDEjzKG5ZC0QCUZBgE5FpLfMsiwHJVIsPOYvY7uFVDpsgQD5pfjF0tVpfZCVoiyEwuJ4Eefn2SkMklZA6cXNWL4SiZCkoZCJYOlQ4SAFJuOcIdrFtPnRPGQYjsJg0EqVuN6n3i0fbxx1wHVtO6sDtZArynBkpqsZAbHuYaZAM9RZCQM
#webhook.verify.token=bhaktisWhatappAccessTokenForHamilton