server.port=8081
spring.application.name=RoomSeervice

spring.datasource.url=jdbc:postgresql://dpg-d66u78h4tr6s73aj8if0-a.virginia-postgres.render.com/test_data2026?sslmode=require
spring.datasource.username=bhakti19
spring.datasource.password=Z2fqeOIzWylY2iSrT2MvfNqzUSvf9g7L

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

whatsapp.base.url=https://graph.facebook.com/${whatsapp.server.version}/${whatsapp.phone.number.id}/messages
whatsapp.phone.number.id=1048663674986407
whatsapp.server.version=v25.0
whatsapp.access.token=EAAwkr5IHAgkBQZBWp1Tc4FX9W4pvdirrlDoHGItmTNbZBV3LMQy190T9fw54CyfhSqiBJMIJ4NgJuujk87S2dodIpJArZAfaDsxa6UQd8xd2MKMYiL5nLkhx08IFxLSXg1SWNQwzcVYdHsOBckVFZAgZBbBhFtENwVBwd6OWHA7T5NAK8yNoJJctrPtgz0cZAAAVSn8kCxfDp2ETgIEwAELzWZA6E3h1IlL1ybgfNjJ89m8ROczHAWeZBXJyfNV3K3rt0w7LfP9cNfidkOIUdTc8bMvH
webhook.verify.token=bhaktisWhatappAccessTokenForHamilton