server.port=8081
spring.application.name=RoomSeervice

spring.datasource.url=jdbc:postgresql://dpg-d66u78h4tr6s73aj8if0-a.virginia-postgres.render.com/test_data2026?sslmode=require
spring.datasource.username=bhakti19
spring.datasource.password=Z2fqeOIzWylY2iSrT2MvfNqzUSvf9g7L

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

whatsapp.base.url=https://graph.facebook.com/${whatsapp.server.version}/${whatsapp.phone.number.id}/messages
whatsapp.phone.number.id=1048663674986407
whatsapp.server.version=v25.0
whatsapp.access.token=EAAwkr5IHAgkBQz4o5AceJP6PK6ni4qKpVZBF31YjFzvc8rKyu6wl430k5oyqhz9IUpl40vDFa4sUWDAz8RavvPEv8ZBJZCakF9vVussr64vwzc55u6v3uwaFrvneOhC4AuQ5OWJ2bnVzo38t4k7GiHP31bzeXSl9j9y9XfLmpl2woh26zupx8ZBPI2qG5A81zbyhDZApHPuDsbxZB3YH03oF1ZCnddsQrD2NYYb1nijqo5ayMpI0KwZBcGpDejaZC2ZBEnwgc7rt82PUZAWQM7D
webhook.verify.token=bhaktisWhatappAccessTokenForHamilton